"use client";
import {useMemo,useState} from "react";
type Monster={name:string,emoji:string,max:number,power:number};
const monsters:Monster[]=[{name:"Pyron",emoji:"🔥",max:100,power:18},{name:"Voltix",emoji:"⚡",max:110,power:16},{name:"Frostfang",emoji:"❄️",max:120,power:15}];
const enemies=[["Ravager","👹",95,15],["Stoneclaw","🗿",120,18],["Nightmaw","🐺",135,20],["Inferno King","😈",170,24]] as const;
export default function Home(){const [level,setLevel]=useState(1);const [coins,setCoins]=useState(120);const [xp,setXp]=useState(0);const [stars,setStars]=useState(3);const [m,setM]=useState(0);const [hp,setHp]=useState(100);const [enemyHp,setEnemyHp]=useState(95);const [log,setLog]=useState("Choose your move.");const enemy=useMemo(()=>enemies[Math.min(level-1,enemies.length-1)], [level]);
function attack(dmg:number,label:string){if(enemyHp<=0)return;const e=Math.max(0,enemyHp-dmg);setEnemyHp(e);if(e===0){const next=level+1;const reward=25+level*10;setCoins(c=>c+reward);setXp(x=>x+35);if(next%6===0)setStars(s=>s+3);setLog(`VICTORY! +${reward} coins • +35 XP`);setTimeout(()=>{setLevel(next);setEnemyHp(80+next*8);setHp(100);},450)}else{const retaliation=enemy[3];const nh=Math.max(0,hp-retaliation);setHp(nh);setLog(`${label} hit for ${dmg}. Enemy strikes for ${retaliation}.`);if(nh===0)setLog("DEFEATED. Use Heal or try again.");}}
function heal(){setHp(100);setLog("❤️ Full Heal restored your HP.");}
function power(){if(stars<1){setLog("Need ⭐ Stars for this power.");return}setStars(s=>s-1);attack(38,"⚡ Rift Power");}
return <main><header><div><div className="brand">MONSTER <b>RIFT</b></div><div className="tag">BATTLE • POWER UP • CONQUER</div></div><div className="stats">⭐ {stars} &nbsp; 🪙 {coins}</div></header><section className="hero"><div><span className="pill">WORLD 1 • LEVEL {level}</span><h1>Enter the <em>Rift.</em></h1><p>Every victory makes the next battle harder. Survive the Rift and become Legendary.</p></div><div className="orb">⚔️</div></section><section className="battle"><div className="card player"><span>YOUR MONSTER</span><h2>{monsters[m].emoji} {monsters[m].name}</h2><div className="bar"><i style={{width:(hp/monsters[m].max*100)+"%"}}/></div><b>{hp} / {monsters[m].max} HP</b></div><div className="vs">VS</div><div className="card enemy"><span>ENEMY</span><h2>{enemy[1]} {enemy[0]}</h2><div className="bar enemybar"><i style={{width:(enemyHp/enemy[2]*100)+"%"}}/></div><b>{enemyHp} / {enemy[2]} HP</b></div></section><div className="log">{log}</div><section className="moves"><button onClick={()=>attack(18,"Quick Attack")}>⚡ Quick Attack</button><button onClick={()=>attack(28,"Heavy Attack")}>💥 Heavy Attack</button><button onClick={power}>🌩️ Rift Power <small>1⭐</small></button><button onClick={heal}>❤️ Full Heal</button></section><section className="bottom"><div>XP <strong>{xp}</strong> • Level <strong>{level}</strong></div><div className="tabs"><button onClick={()=>setM((m+1)%monsters.length)}>👾 Monster</button><button onClick={()=>setLog("⭐ Powers: Lightning • Shield • Freeze • Rage • Mega Attack")}>⭐ Powers</button><button onClick={()=>setLog("🏆 Global leaderboard coming with cloud save.")}>🏆 Rank</button></div></section></main>}