"use client";
import {useEffect,useState} from "react";
type M={name:string;emoji:string;max:number;power:number;skill:string};
type S={world:string;enemy:string;emoji:string;hp:number;atk:number;boss:boolean;reward:number};
type Save={level:number;coins:number;xp:number;stars:number;monster:number;wins:number;hp:number};
declare global{interface Window{show_11966468?:((options?:any)=>Promise<any>)&((type:string)=>Promise<any>)}}
const monsters:M[]=[
{name:"Pyron",emoji:"🔥",max:120,power:22,skill:"Ember Surge"},
{name:"Voltix",emoji:"⚡",max:135,power:20,skill:"Volt Crash"},
{name:"Frostfang",emoji:"❄️",max:150,power:18,skill:"Glacial Bite"}];
const worlds=["Emerald Wilds","Burning Expanse","Frozen Abyss","Shadow Citadel","Cosmic Rift"];
const names=[["Ravager","👹"],["Stoneclaw","🗿"],["Nightmaw","🐺"],["Thorn Warden","🌿"],["Ash Reaper","🔥"],["Dune Tyrant","🦂"],["Blazehorn","🦬"],["Inferno King","😈"],["Frost Wraith","👻"],["Glacier Fang","🐲"],["Ice Colossus","🧊"],["Winter Queen","👑"],["Void Stalker","🕷️"],["Shadowfang","🐺"],["Dread Knight","⚔️"],["Rift Emperor","☠️"],["Star Eater","🌌"],["Nova Beast","☄️"],["Astral Titan","👾"],["Rift Sovereign","🌑"]] as const;
const stages:S[]=names.map(([enemy,emoji],i)=>({world:worlds[Math.floor(i/4)],enemy,emoji,hp:95+i*18+(i%4===3?45:0),atk:13+i*2+(i%4===3?6:0),boss:i%4===3,reward:35+i*12+(i%4===3?80:0)}));
const initial:Save={level:1,coins:250,xp:0,stars:6,monster:0,wins:0,hp:120};
const MONETAG_SRC="https://libtl.com/sdk.js";
const MONETAG_ZONE="11966468";

function Character({kind,enemy=false,boss=false}:{kind:string;enemy?:boolean;boss?:boolean}){const tone=enemy?"#ff4d67":"#ff6b35";return <div className={"character "+(enemy?"enemy-character ":"player-character ")+(boss?"boss-character":"")}><div className="aura" style={{background:tone}}/><svg viewBox="0 0 220 220" role="img" aria-label={kind+" battle character"}><defs><linearGradient id={"body-"+(enemy?"e":"p")} x1="0" x2="1"><stop offset="0" stopColor={enemy?"#6d1832":"#7a1f14"}/><stop offset="1" stopColor={enemy?"#ff496b":"#ff8a35"}/></linearGradient></defs><ellipse cx="110" cy="194" rx="65" ry="12" fill="rgba(0,0,0,.38)"/><path d={enemy?"M58 130 Q45 92 68 58 Q94 24 130 43 Q169 52 163 102 L151 153 Q128 179 88 163Z":"M60 139 Q47 92 74 55 Q106 20 143 50 Q170 74 157 121 L145 165 Q107 183 75 160Z"} fill={"url(#body-"+(enemy?"e":"p")+")"} stroke={tone} strokeWidth="4"/><path d="M78 72 Q110 47 145 71 L139 111 Q110 132 79 109Z" fill="#171923" stroke="#f7f8fb" strokeWidth="3"/><circle cx="96" cy="87" r="9" fill="#fff"/><circle cx="124" cy="87" r="9" fill="#fff"/><circle cx="98" cy="88" r="4" fill={tone}/><circle cx="122" cy="88" r="4" fill={tone}/><path d="M92 108 Q110 121 130 106" fill="none" stroke="#fff" strokeWidth="5" strokeLinecap="round"/>{enemy?<><path d="M66 64 L39 39 L75 49Z" fill="#ff496b"/><path d="M151 59 L181 35 L164 72Z" fill="#ff496b"/></>:<><path d="M75 55 L56 24 L91 43Z" fill="#ffb347"/><path d="M139 53 L164 20 L153 65Z" fill="#ffb347"/></>}<path d="M64 128 Q37 136 27 160" fill="none" stroke={tone} strokeWidth="15" strokeLinecap="round"/><path d="M154 126 Q183 136 193 158" fill="none" stroke={tone} strokeWidth="15" strokeLinecap="round"/></svg><div className="character-name">{kind}</div></div>}
export default function Home(){
const [s,setS]=useState<Save>(initial),[eh,setEh]=useState(stages[0].hp),[log,setLog]=useState("Choose your move. Every stage gets harder."),[ready,setReady]=useState(false),[user,setUser]=useState(""),[adReady,setAdReady]=useState(false);
const m=monsters[s.monster],stage=stages[Math.min(s.level-1,19)],done=s.level>20,dead=s.hp<=0;
useEffect(()=>{try{const x=localStorage.getItem("monster-rift-save");if(x)setS({...initial,...JSON.parse(x)});}catch{}const w=window as Window&{Telegram?:{WebApp?:{ready:()=>void;expand:()=>void;initDataUnsafe?:{user?:{first_name?:string;username?:string}}}}};const tg=w.Telegram?.WebApp;if(tg){tg.ready();tg.expand();const u=tg.initDataUnsafe?.user;if(u)setUser(u.first_name||u.username||"");}else{const sc=document.createElement("script");sc.src="https://telegram.org/js/telegram-web-app.js?63";sc.onload=()=>{const t=w.Telegram?.WebApp;if(t){t.ready();t.expand();}};document.head.appendChild(sc);}
if(!document.querySelector('script[data-monster-rift-monetag]')){const ad=document.createElement("script");ad.src=MONETAG_SRC;ad.async=true;ad.dataset.zone=MONETAG_ZONE;ad.dataset.sdk="show_"+MONETAG_ZONE;ad.dataset.monsterRiftMonetag="1";ad.onload=()=>setAdReady(typeof window.show_11966468==="function");ad.onerror=()=>setLog("Ad service unavailable. Battle is still playable.");document.head.appendChild(ad);}const poll=window.setInterval(()=>{if(typeof window.show_11966468==="function"){setAdReady(true);window.clearInterval(poll);}},500);setReady(true);return()=>window.clearInterval(poll);},[]);
useEffect(()=>{if(ready)localStorage.setItem("monster-rift-save",JSON.stringify(s));},[s,ready]);
useEffect(()=>{if(ready&&!done){setEh(stage.hp);setS(v=>({...v,hp:monsters[v.monster].max}));}},[s.level,ready]);
function win(){const n=s.level+1;if(n>20){setS(v=>({...v,level:21,wins:v.wins+1,coins:v.coins+stage.reward,xp:v.xp+50,stars:v.stars+10}));setLog("🏆 RIFT CONQUERED! +"+stage.reward+" coins • +50 XP • +10 ⭐");return;}const bonus=stage.boss?10:n%6===0?3:0;setS(v=>({...v,level:n,coins:v.coins+stage.reward,xp:v.xp+50,stars:v.stars+bonus,wins:v.wins+1,hp:monsters[v.monster].max}));setLog((stage.boss?"👑 BOSS CLEARED! ":"VICTORY! ")+"+"+stage.reward+" coins • +50 XP"+(bonus?" • +"+bonus+" ⭐":""))}
function hit(d:number,label:string){if(dead||done||eh<=0)return false;const n=Math.max(0,eh-d);setEh(n);if(n===0){win();return true;}setS(v=>({...v,hp:Math.max(0,v.hp-stage.atk)}));setLog(label+" dealt "+d+" damage. "+stage.enemy+" hits for "+stage.atk+".");return true;}
function power(label:string,cost:number,dmg:number){if(dead||done||eh<=0){setLog(dead?"❤️ Heal or revive first.":"Battle is already complete.");return;}if(s.stars<cost){setLog("Need "+cost+" ⭐ for "+label+".");return;}setS(v=>({...v,stars:v.stars-cost}));hit(dmg,label);}
function heal(){if(done)return;if(s.hp<=0){setLog("❤️ Watch a revive ad to return to battle.");return;}setS(v=>({...v,hp:m.max}));setLog("❤️ Full Heal restored HP.");}
function shield(){if(done||dead){setLog(dead?"❤️ Revive first.":"Battle is complete.");return;}if(s.stars<3){setLog("Need 3 ⭐ for Shield.");return;}setS(v=>({...v,stars:v.stars-3,hp:Math.min(m.max,v.hp+45)}));setLog("🛡️ Shield restored 45 HP.");}
function swap(){if(dead){setLog("❤️ Revive first.");return;}const n=(s.monster+1)%3;setS(v=>({...v,monster:n,hp:monsters[n].max}));setLog("👾 Switched to "+monsters[n].name+".");}
function reset(){localStorage.removeItem("monster-rift-save");setS(initial);setEh(stages[0].hp);setLog("New Rift run started.");}
async function rewarded(action:"revive"|"coins"){let tries=0;while(typeof window.show_11966468!=="function"&&tries<20){await new Promise(r=>window.setTimeout(r,250));tries++;}if(typeof window.show_11966468!=="function"){setLog("📺 Monetag is not available right now. Try again shortly.");return;}setAdReady(true);try{setLog("📺 Watching reward ad…");await window.show_11966468();if(action==="revive"){setS(v=>({...v,hp:monsters[v.monster].max}));setLog("❤️ Revive claimed! Full HP restored.");}else{setS(v=>({...v,coins:v.coins+100}));setLog("🎁 Reward claimed! +100 coins.");}}catch{setLog("Ad could not be completed. No reward was given.");}}
useEffect(()=>{if(!ready||done||!adReady)return;const t=window.setTimeout(()=>{try{window.show_11966468?.({type:"inApp",inAppSettings:{frequency:2,capping:0.1,interval:30,timeout:5,everyPage:false}});}catch{}},5000);return()=>window.clearTimeout(t);},[ready,done,adReady,s.level]);
if(!ready)return <main><div className="loading">Loading Rift...</div></main>;
const world=Math.floor((Math.min(s.level,20)-1)/4)+1,progress=(s.xp%200)/2;
return <main><header><div><div className="brand">MONSTER <b>RIFT</b></div><div className="tag">BATTLE • POWER UP • CONQUER</div></div><div className="stats">⭐ {s.stars} &nbsp; 🪙 {s.coins}</div></header>
<section className="hero"><div><span className="pill">WORLD {world} • {stage.world.toUpperCase()} • LEVEL {Math.min(s.level,20)}</span><h1>Enter the <em>Rift.</em></h1><p>{user?"Welcome, "+user+". ":""}20 launch stages • 5 worlds • hard bosses • original monsters.</p><button className="primary enter-rift" onClick={()=>document.getElementById("battle-arena")?.scrollIntoView({behavior:"smooth",block:"start"})}>⚔️ ENTER THE RIFT</button></div><div className="orb">⚔️</div></section>
{done?<section className="complete card"><div className="boss-mark">👑</div><h2>RIFT CONQUERED</h2><p>You cleared every launch stage.</p><button className="primary" onClick={reset}>Restart Run</button></section>:<><section id="battle-arena" className="battle"><div className="card fighter-card"><span>YOUR MONSTER</span><Character kind={m.name}/><h2>{m.emoji} {m.name}</h2><div className="bar"><i style={{width:(s.hp/m.max*100)+"%"}}/></div><b>{s.hp} / {m.max} HP</b><div className="skill">{m.skill}</div></div><div className="vs">VS</div><div className={"card fighter-card "+(stage.boss?"boss":"")}><span>{stage.boss?"👑 BOSS":"ENEMY"}</span><Character kind={stage.enemy} enemy boss={stage.boss}/><h2>{stage.emoji} {stage.enemy}</h2><div className="bar enemybar"><i style={{width:(eh/stage.hp*100)+"%"}}/></div><b>{eh} / {stage.hp} HP</b></div></section>
<div className="log">{log}</div><section className="moves">
<button onClick={()=>hit(m.power,"⚡ Quick Attack")}>⚡ Quick Attack</button><button onClick={()=>hit(m.power+14,"💥 Heavy Attack")}>💥 Heavy Attack</button><button onClick={()=>power("🌩️ Lightning",5,m.power+45)}>🌩️ Lightning <small>5⭐</small></button><button onClick={()=>power("❄️ Freeze",6,m.power+55)}>❄️ Freeze <small>6⭐</small></button><button onClick={shield}>🛡️ Shield <small>3⭐</small></button><button onClick={()=>power("😡 Rage",8,m.power+70)}>😡 Rage <small>8⭐</small></button><button onClick={()=>power("💥 Mega",10,m.power+95)}>💥 Mega <small>10⭐</small></button><button onClick={heal}>❤️ Full Heal</button></section>
<section className="ad-rewards"><div><b>🎁 Free Bonus</b><span>Watch an ad to earn rewards</span></div><button onClick={()=>rewarded("coins")}>📺 +100 Coins</button><button onClick={()=>rewarded("revive")}>❤️ Revive</button></section>
<section className="progress"><div><span>RIFT XP</span><b>{s.xp} XP</b></div><div className="bar"><i style={{width:progress+"%"}}/></div></section>
<section className="bottom"><div>Stage <strong>{s.level}</strong>/20 • Wins <strong>{s.wins}</strong></div><div className="tabs"><button onClick={swap}>👾 Monster</button><button onClick={()=>setLog("⭐ Powers: Lightning • Freeze • Shield • Rage • Mega.")}>⭐ Powers</button><button onClick={()=>setLog("🏆 Global leaderboard: server validation is the next backend phase.")}>🏆 Rank</button><button onClick={reset}>↻ Reset</button></div></section></>}</main>}
